### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by seanoshea** [rgbycch/rgbycch-rest#8]
Having a bit of hassle getting the API up and running. It's been ages since I've done any server side Java work & I haven't used maven before, but here's what Im seeing in the console:

```
sean:rgbycch-rest Sean$ mvn clean install -DskipTests
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] rugby coach rest api base
[INFO] rugby coach model
[INFO] rugby coach persistence
[INFO] rugby coach service
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rugby coach rest api base 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rgbycch-rest-api ---
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ rgbycch-rest-api ---
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) > generate-sources @ rgbycch-rest-api     >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) < generate-sources @ rgbycch-rest-api <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ rgbycch-rest-api ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ rgbycch-rest-api ---
[INFO] Installing /Users/Sean/dev/github/rgbycch-rest/pom.xml to     /Users/Sean/.m2/repository/com/gffny/rgbycch-rest-api/1.0-SNAPSHOT/rgbycch-rest-api-1.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rugby coach model 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rgbycch-model ---
[INFO] Deleting /Users/Sean/dev/github/rgbycch-rest/rgbycch-model/target
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ rgbycch-model ---
[WARNING] No processors specified. Using default discovery mechanism.
[ERROR] JVM is not suitable for processing annotation! ToolProvider.getSystemJavaCompiler() is null.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ rgbycch-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ rgbycch-model ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to /Users/Sean/dev/github/rgbycch-rest/rgbycch-model/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather     than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] rugby coach rest api base .......................... SUCCESS [  4.645 s]
[INFO] rugby coach model .................................. FAILURE [  8.514 s]
[INFO] rugby coach persistence ............................ SKIPPED
[INFO] rugby coach service ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.872 s
[INFO] Finished at: 2015-07-25T17:30:06+01:00
[INFO] Final Memory: 18M/126M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project rgbycch-model: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rgbycch-model
```

My .bash_profile looks like:

```
export PATH=${PATH}:/Users/Sean/bin
export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/"
```

Dunno if I'm missing out on something?

**Comment by gffny** [comment]
Looks like you'll need to install a JDK on that dev environment of yours. Run "javac -version" to see if you have one installed already. Install the Java 8 development kit from <a href="http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html">here</a> if you don't have it already

**Comment by seanoshea** [comment]
OK - getting a bit closer. Will see if I can figure this out (FWIW, I'm on the 1.8 version of java/javac).

``` ruby
sean:rgbycch-rest Sean$ javac -version
javac 1.8.0_51
sean:rgbycch-rest Sean$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
sean:rgbycch-rest Sean$ 
```

``` ruby
sean:rgbycch-rest Sean$ mvn -e jetty:run -DskipTests
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] rugby coach rest api base
[INFO] rugby coach model
[INFO] rugby coach persistence
[INFO] rugby coach service
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rugby coach rest api base 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jetty-maven-plugin:9.2.9.v20150224:run (default-cli) > test-compile @ rgbycch-rest-api >>>
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ rgbycch-rest-api ---
[INFO] 
[INFO] <<< jetty-maven-plugin:9.2.9.v20150224:run (default-cli) < test-compile @ rgbycch-rest-api <<<
[INFO] 
[INFO] --- jetty-maven-plugin:9.2.9.v20150224:run (default-cli) @ rgbycch-rest-api ---
[INFO] Logging initialized @2566ms
[INFO] Configuring Jetty for project: rugby coach rest api base
[INFO] Skipping Jetty start: jetty.skip==true
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rugby coach model 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jetty-maven-plugin:9.2.9.v20150224:run (default-cli) > test-compile @ rgbycch-model >>>
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ rgbycch-model ---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ rgbycch-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ rgbycch-model ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 17 source files to /Users/Sean/dev/github/rgbycch-rest/rgbycch-model/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ rgbycch-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Sean/dev/github/rgbycch-rest/rgbycch-model/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ rgbycch-model ---
[INFO] No sources to compile
[INFO] 
[INFO] <<< jetty-maven-plugin:9.2.9.v20150224:run (default-cli) < test-compile @ rgbycch-model <<<
[INFO] 
[INFO] --- jetty-maven-plugin:9.2.9.v20150224:run (default-cli) @ rgbycch-model ---
[INFO] Configuring Jetty for project: rugby coach model
[INFO] Skipping Jetty start: jetty.skip==true
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rugby coach persistence 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jetty-maven-plugin:9.2.9.v20150224:run (default-cli) > test-compile @ rgbycch-persistence >>>
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ rgbycch-persistence ---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ rgbycch-persistence ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Sean/dev/github/rgbycch-rest/rgbycch-persistence/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ rgbycch-persistence ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ rgbycch-persistence ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Sean/dev/github/rgbycch-rest/rgbycch-persistence/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ rgbycch-persistence ---
[INFO] No sources to compile
[INFO] 
[INFO] <<< jetty-maven-plugin:9.2.9.v20150224:run (default-cli) < test-compile @ rgbycch-persistence <<<
[INFO] 
[INFO] --- jetty-maven-plugin:9.2.9.v20150224:run (default-cli) @ rgbycch-persistence ---
[INFO] Configuring Jetty for project: rugby coach persistence
[INFO] Skipping Jetty start: jetty.skip==true
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rugby coach service 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jetty-maven-plugin:9.2.9.v20150224:run (default-cli) > test-compile @ rgbycch-service >>>
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ rgbycch-service ---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ rgbycch-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Sean/dev/github/rgbycch-rest/rgbycch-service/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ rgbycch-service ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ rgbycch-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Sean/dev/github/rgbycch-rest/rgbycch-service/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ rgbycch-service ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< jetty-maven-plugin:9.2.9.v20150224:run (default-cli) < test-compile @ rgbycch-service <<<
[INFO] 
[INFO] --- jetty-maven-plugin:9.2.9.v20150224:run (default-cli) @ rgbycch-service ---
[WARNING] The POM for com.oracle:ojdbc7:jar:12.1.0.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] rugby coach rest api base .......................... SUCCESS [  0.818 s]
[INFO] rugby coach model .................................. SUCCESS [  2.302 s]
[INFO] rugby coach persistence ............................ SUCCESS [  0.363 s]
[INFO] rugby coach service ................................ FAILURE [  0.419 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.336 s
[INFO] Finished at: 2015-07-28T21:23:54+01:00
[INFO] Final Memory: 48M/291M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224:run (default-cli) on project rgbycch-service: Execution default-cli of goal org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224:run failed: Plugin org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224 or one of its dependencies could not be resolved: Failure to find com.oracle:ojdbc7:jar:12.1.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224:run (default-cli) on project rgbycch-service: Execution default-cli of goal org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224:run failed: Plugin org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224 or one of its dependencies could not be resolved: Failure to find com.oracle:ojdbc7:jar:12.1.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224:run failed: Plugin org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224 or one of its dependencies could not be resolved: Failure to find com.oracle:ojdbc7:jar:12.1.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224 or one of its dependencies could not be resolved: Failure to find com.oracle:ojdbc7:jar:12.1.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:218)
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:422)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:385)
    at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:102)
    ... 21 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.oracle:ojdbc7:jar:12.1.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:210)
    ... 26 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.oracle:ojdbc7:jar:12.1.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
    at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
    at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    ... 29 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rgbycch-service
sean:rgbycch-rest Sean$
```

**Comment by gffny** [comment]
I just fixed that issue. Looks like I had a dependency on OJDBC (oracle 
java database connector) in the dependencies, which Oracle kindly does 
not have hosted in a an public dependency management repository.

**Comment by seanoshea** [comment]
I'm up and running. Cheers for that!
